package fr.achabitation.infrastructure.entity;

public enum AuditAction {
    USER_REGISTERED,
    TRIP_CREATED,
    TRIP_UPDATED,
    TRIP_MEMBER_JOINED,
    PERSON_CREATED,
    PERSON_UPDATED,
    PERSON_DISABLED,
    PERSON_LINKED_TO_USER,
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    INVITATION_CREATED,
    INVITATION_REVOKED,
    EXPORT_GENERATED
}
